'\" t
.\" Note: this must be run through tbl before nroff.
.\" The magic cookie on the first line triggers this under some man program
.TH MTEST 1 local
.SH NAME
mtest \- tests the mtools configuration files
.SH SYNOPSIS
.B mtest
.SH DESCRIPTION
.I Mtest
reads the mtools configuration files, and prints the cumulative
configuration to stdout. The output can be used as a configuration
file itself (although you might want to remove redundant clauses).
You may use this program to convert old-style configuration files into
new style configuration files.
.SH SEE ALSO
mtools(5)
.SH BUGS
